apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: asset-testing-deployment
  name: asset-testing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asset-testing-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: asset-testing-deployment
    spec:
      containers:
      - image: alahari9/asset-testing:latest
        name: asset-testing
        resources: {}
status: {}
